name: Daggers
author: DreamerBoy
version: ${project.version}
api-version: 1.16
main: com.dreamerboy.daggers.Daggers
description: daggers by dreamerboy
depend: [ProjectKorra]
permissions:
  bending.ability.daggerthrow:
    default: true
  bending.ability.daggerthrow.cosmetics:
    default: true
  bending.ability.daggerthrow.normal:
    default: true
  bending.ability.daggerthrow.electro:
    default: true
  bending.ability.daggerthrow.poisonous:
    default: true
  bending.ability.daggerthrow.forcefield:
    default: true
  bending.ability.daggerthrow.explosive:
    default: true